LOG_PATH: "logs"
GAME_RULES_DATA_PATH: "data/game_rules"
CHROMA_DB_PATH: "chromadb"
CHROMA_DB_FILE: "chroma.sqlite3"

EVALUATION_DATA_PATHS: 
  - "data/evaluation_data/chess_questions.json"
  - "data/evaluation_data/monopoly_questions.json"
  - "data/evaluation_data/uno_questions.json"
  - "data/evaluation_data/ticket_to_ride_questions.json"
RESULTS_CSV_PATH: "artifacts/evaluation_results.csv"

CHUNK_SIZE: 800
CHUNK_OVERLAP: 80
BATCH_SIZE: 64
K: 5

# EMBEDDING_MODEL: "sentence-transformers/all-MiniLM-L6-v2"
EMBEDDING_MODEL: "BAAI/bge-small-en"
GENERATION_MODEL: "llama3.2"